name: extended_text_library
description: package library for extended_text and extended_text_field,provide common base class.
version: 11.0.2
homepage: https://github.com/fluttercandies/extended_text_library

environment:
  sdk: '>=2.17.0 <4.0.0'
  flutter: ">=3.0.5"

dependencies:
  flutter:
    sdk: flutter

